apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../podmonitor
- ../prometheus-rules
- scc.yaml
- scc-clusterrole.yaml
- scc-clusterrolebinding.yaml
- datasource.yaml
- dashboard.yaml
- dashboard-memory.yaml
patches:
- patch: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: kubevirt-metrics-exporter
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
  target:
    kind: DaemonSet
    name: kubevirt-metrics-exporter
images:
- name: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newName: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newTag: latest
